# arx.R
# 
# simulation of time series regression with AR(1) distarbance term
#      y[t] = beta x[t] + v[t]
#      v[t] = rho v[t-1] + e[t]
#      e[t] ~ N(0, sigma^2)
#
# written by: shig_ono (elsur2005[at-mark]v003.vaio.ne.jp)

makeData.1 <- function(){
  # purpose: make dataset for simulation
  # return:
  #   a data frame, a row is trial x time
  #   $nID:        trial ID across all rho (1:11000)
  #   $gRho:       rho 
  #   $nIter:      trial ID in each rho (1:1000)
  #   $t:          time point(1:100)
  #   $x_centered: x, drawn from unif(-1, 1), centered in each trial
  #   $y_centered: y, centered in each trial
  
  # - - - - 
  agRHO     <- seq(from = 0, to = 1, by = 0.1)  # rho
  nNUMITER  <- 1000  # number of trial in each rho
  nT        <- 100   # length of time series
  nT_PAST   <- 10    # length of past time series (to set reasonable variance in v[1])
  # - - - - 
  
  set.seed(123)
  
  dfTrial <- crossing(
    gRho  = agRHO, 
    nIter = seq_len(nNUMITER)
  ) %>%
    mutate(nID = seq_len(nrow(.)))
  
  out <- dfTrial %>%
    # loop for each nID
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      # lIn: spec of this trial
      lIn <- as.list(dfIn)
      # agX
      agX <- runif(nT+nT_PAST, min = -1, max = 1)
      # agV
      agEpsilon <- rnorm(nT+nT_PAST, mean = 0, sd = 1)
      agV <- stats::filter(agEpsilon, lIn$gRho, method = "recursive")
      # agY
      agY <- agX + agV
      # remove past 
      agX <- agX[-(1:nT_PAST)]
      agY <- agY[-(1:nT_PAST)]
      # output
      tibble(
        nID        = lIn$nID,
        gRho       = lIn$gRho,
        nIter      = lIn$nIter,
        t          = seq_len(nT),
        x          = agX, 
        y          = agY,
        x_centered = scale(agX, center = T, scale = F),
        y_centered = scale(agY, center = T, scale = F)
      )
    })
  return(out)
}
makeDFtest.1 <- function(dfData){
  # purpose: run Dickey-Fuller test for y[t] in each trial
  # args: 
  #   dfData: generated by makeData.1()
  # return: 
  #   a data frame, a row is trial
  #   $nID
  #   $gRho
  #   $nD:    {0(stationary), 1(unit root)}
  #           based on Dickey-Fuller test, 5% level
  
  library(urca)
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oDFTest <- ur.df(dfIn$y_centered, type = "none", lags = 1)
      nD <- if_else(oDFTest@teststat[1,1] < oDFTest@cval[2], 0, 1)
      
      tibble(
        nID    = dfIn$nID[1],
        gRho   = dfIn$gRho[1],
        nD     = nD
      )
    })
  # print(out)
  return(out)
}
makeEstA1.1 <- function(dfData){
  # purpose: estimation of OLS regression  model
  #          under assumption that rho = 0
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho:   NA
  #   $gEstBeta
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oModel <- lm(y_centered ~ 0 + x_centered, data = dfIn)
      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = NA, 
        gEstBeta = coef(oModel)[1]
      )
      # print(out)
      # stop()
      return(out)
    }
    )
  return(out)
}
makeEstA3.1 <- function(dfData){
  # purpose: estimation of OLS regression  model
  #          under assumption that rho = 1
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho:   NA
  #   $gEstBeta
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oModel <- lm(diff(y_centered) ~ 0 + diff(x_centered), data = dfIn)
      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = NA, 
        gEstBeta = coef(oModel)[1]
      )
      # print(out)
      # stop()
      return(out)
    }
  )
  return(out)
}
makeEstB2.1 <- function(dfData){
  # purpose: estimation of AR(1) error model by forecast::Arima()
  #          under assumption that |rho| < 1
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  
  library(forecast)
  
  out <- dfData %>%
    ### these nID raise the error below
    ### Error in solve.default(res$hessian * n.used, A) : 
    ### Lapack routine dgesv: system is exactly singular: U[1,1] = 0
    ### filter(nID %in% c(10463, 10589, 10936)) %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oModel <- tryCatch({
        Arima(
          y            = dfIn$y_centered,
          include.mean = FALSE,
          order        = c(1, 0, 0),
          xreg         = dfIn$x_centered ,
          method       = "ML"
        )}, 
        error = function(e){
          cat("ML estimation is failed. run CSS-ML estimation instead...\n")
          Arima(
            y            = dfIn$y_centered,
            include.mean = FALSE,
            order        = c(1, 0, 0),
            xreg         = dfIn$x_centered
          )
        }
      )

      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = oModel$coef[1], 
        gEstBeta = oModel$coef[2]
      )
      # print(out)
      # stop()
      return(out)
    }
  )
  return(out)
}
makeEstB3.1 <- function(dfData){
  # purpose: estimation of ARIMA(0,1,0) error model by forecast::Arima()
  #          under assumption that |rho| = 1
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  
  library(forecast)
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oModel <- Arima(
          y            = dfIn$y_centered,
          include.mean = FALSE,
          order        = c(0, 1, 0),
          xreg         = dfIn$x_centered ,
          method       = "ML"
      )
      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = NA, 
        gEstBeta = oModel$coef[1]
      )
      return(out)
    }
    )
  return(out)
}
makeEstB4.1 <- function(dfEstB2, dfEstB3, dfDFtest){
  # purpose: select B2 or B3 based on DF test
  # args: 
  #   dfEstB2: generated by makeEstB2.1()
  #   dfEstB3: generated by makeEstB3.1()
  #   dfDFtest: generated by makeDFtest.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  #   $nD:       {0:B2, 1:B3}
  
  out <- bind_rows(
    dfEstB2 %>% mutate(nD = 0), 
    dfEstB3 %>% mutate(nD = 1)
  ) %>%
    inner_join(
      dfDFtest %>% dplyr::select(nID, nD), 
      by = c("nID", "nD")
    )
  # print(summary(out))
  
  return(out)
}
makeEstC2.1 <- function(dfData){
  # purpose: estimation of AR(1) error model by nlme::gls()
  #          under assumption that |rho| < 1
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  
  library(nlme)
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      oModel <- gls(
        y_centered ~ 0 + x_centered, 
        corr = corARMA(p=1, q=0), 
        data = dfIn
      )
      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = coef(oModel$modelStruct$corStruct, unconstrained=FALSE), 
        gEstBeta = coef(oModel)[1]
      )
      # print(out)
      # stop()
      return(out)
    }
    )
  return(out)
}
makeEstD5.1 <- function(dfData){
  # purpose: estimation of AR(1) error model by KFAS
  # args: 
  #   dfData: generated be makeData.1()
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  
  library(KFAS)
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      
      mgZ <- array(dim = c(1, 2, nrow(dfIn)))
      mgZ[1,1,] <- as.vector(dfIn$x_centered)
      mgZ[1,2,] <- 1
      
      oModel <- SSModel(
        dfIn$y_centered ~ -1 + SSMcustom(
          Z     = mgZ,
          T     = matrix(c(1, 0, 0, 1), nrow = 2), # 最後の要素がphi
          R     = matrix(c(1, 0, 0, 1), nrow = 2), 
          Q     = matrix(c(0, 0, 0, 1), nrow = 2), # 最後の要素がsigma
          P1    = matrix(c(0,0,0,0), nrow = 2), 
          P1inf = matrix(c(1,0,0,1), nrow = 2)
        ),
        H = matrix(0)
      )
      sub_update <- function(par, model){
        # par: (sigmaの対数, ARパラメータ)
        # model: 現在のモデル
        model$T[2,2,1] <- par[2]
        model$Q[2,2,1] <- exp(par[1])
        return(model)
      }
      oFitted <- fitSSM(
        oModel, 
        inits = c(log(var(dfIn$x_centered)/2), 0.5) , 
        updatefn = sub_update, 
        lower = c(-10, -2),
        upper = c(+10, +2),
        method = "L-BFGS-B"
      )
      oEstimated <- KFS(oFitted$model)
      
      out <- tibble(
        nID      = dfIn$nID[1], 
        gRho     = dfIn$gRho[1],
        gEstRho  = oEstimated$model$T[2,2,1], 
        gEstBeta = oEstimated$alphahat[1,1]
      )
      return(out)
    }
    )
  return(out)
}
makeEstE5.1 <- function(dfData, BASEDIR, WORKDIR){
  # purpose: estimation of AR(1) error model by Mplus
  # args: 
  #   dfData: generated be makeData.1()
  #   BASEDIR
  #   WORKDIR
  # return: 
  #   a data frame, a row is a trial
  #   $nID
  #   $gRho
  #   $gEstRho
  #   $gEstBeta
  
  library(MplusAutomation)
  
  # - - - - 
  sINPFILE = "estE5.inp"
  # - - - - 
  
  file.copy(
    paste0(BASEDIR, "/", sINPFILE), 
    paste0(WORKDIR, "/", sINPFILE)
  )
  
  out <- dfData %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      write_tsv(
        dfIn %>% dplyr::select(y_centered, x_centered), 
        paste0(WORKDIR, "/estE5_data.dat"), 
        col_names = F
      )
      runModels(paste0(WORKDIR, "/", sINPFILE))
      dfResult <- read_table2 (
        paste0(WORKDIR, "/estE5_result.dat"), 
        col_names = FALSE,
        col_types = cols(.default = col_double())
      )
      out <- tibble(
        nID       = dfIn$nID[1],
        gRho      = dfIn$gRho[1],
        gEstBeta  = dfResult$X2[1],
        gEstRho   = dfResult$X1[1]
      )
      # print(out)
      # stop()
      return(out)
    })
  # print(out)
  return(out)
}
makeEstF.1 <- function(dfData, oModel){
  
  out <- dfData %>%
    filter(nIter %in% 1:100) %>%
    split(., .$nID) %>%
    map_dfr(function(dfIn){
      cat("nID=", dfIn$nID[1], "...\n")
      lData <- list(
        T = nrow(dfIn),
        y = dfIn$y_centered, 
        x = dfIn$x_centered
      )
      oFit <- sampling(
        oModel, 
        data   = lData, 
        chains = 3, 
        iter   = 1000
      )
      print(oFit)
      lSample <- rstan::extract(oFit)
      out <- tibble(
        nID       = dfIn$nID[1],
        gRho      = dfIn$gRho[1],
        gEstBeta  = mean(lSample$beta),
        gEstRho   = mean(lSample$rho)
      )
      # print(out)
      # stop()
      return(out)
    })
  # print(out)
  return(out)
}
makeEstStat.1 <- function(
  dfEstA1, dfEstA3, dfEstB2, dfEstB3, dfEstB4, dfEstC2, dfEstD5,
  dfEstE5, dfEstF2, dfEstF5
){
  
  out <- bind_rows(
    dfEstA1 %>% mutate(nModel = 1), 
    dfEstA3 %>% mutate(nModel = 2),
    dfEstB2 %>% mutate(nModel = 3),
    dfEstB3 %>% mutate(nModel = 4),
    dfEstB4 %>% mutate(nModel = 5),
    dfEstC2 %>% mutate(nModel = 6),
    dfEstD5 %>% mutate(nModel = 7),
    dfEstE5 %>% mutate(nModel = 8),
    dfEstF2 %>% mutate(nModel = 9),
    dfEstF5 %>% mutate(nModel = 10)
  ) %>%
    group_by(gRho, nModel) %>%
    summarize( 
      gMean = mean(gEstBeta),
      gRMSE = sqrt(mean( (gEstBeta - 1)^2 )) 
    ) %>%
    ungroup() %>%
    mutate(
      fModel = factor(
        nModel, 
        levels = 1:10, 
        labels = c("A1", "A3", "B2", "B3", "B4", "C2", "D5", "E5", "F2", "F5")
      ),
      fApproach = factor(
        c(1,3,2,3,4,2,5,5,2,5)[nModel], 
        levels = 1:5, 
        labels = c("1.rho=0", "2.|rho|<1", "3.rho=1", "4.DF test", "5.no assumption")
      ), 
      fEstimator = factor(
        c(1,1,2,2,2,3,4,5,6,6)[nModel], 
        levels = 1:6, 
        labels = c("A.OLS", "B.ML", "C.FGLS", "D.Kalman", "E.Bayes(Mplus)", "F.Bayes(Stan)")
      )
    )
  return(out)
  
}
plotData.1 <- function(dfData, WORKDIR){
  # plot time series
  
  agRho <- sort(unique(dfData$gRho))
  
  dfPlot <- dfData %>%
    filter(nIter == 3) %>%
    dplyr::select(gRho, t, x_centered, y_centered) %>%
    pivot_longer(cols = c(x_centered, y_centered), names_to = "sVar", values_to = "gValue") %>%
    mutate(
      fRho = factor(gRho, levels = agRho, labels = paste0("rho=", agRho))
    )
  # print(dfPlot)
  # stop()
    
  g <- ggplot(data = dfPlot, aes(x = t, y = gValue, group = sVar, color = sVar))
  g <- g + geom_line()
  g <- g + geom_hline(yintercept = 0, color ="gray")
  g <- g + scale_color_discrete(name = NULL)
  g <- g + labs(y = "value")
  g <- g + facet_wrap(~ fRho, ncol = 6)
  g <- g + theme_bw()
  g <- g + theme(
    legend.position="bottom",
    axis.text.x = element_text(size = 7)
  )
  print(g)
  ggsave(paste0(WORKDIR, "/plotData.1.jpg"), width = 12, height = 8, units = "cm")

}
plotDFtest.1 <- function(dfDFtest, WORKDIR){
  # plot ratio of unit-root time series

  agRho <- sort(unique(dfData$gRho))
  
  dfPlot <- dfDFtest %>%
    group_by(gRho) %>%
    summarize(gProp = mean(nD)) %>%
    ungroup() %>%
    mutate(
      fRho = factor(gRho, levels = agRho, labels = paste0("rho=", agRho))
    )
  print(dfPlot)
  
  g <- ggplot(data = dfPlot, aes(x = fRho, y = gProp))
  g <- g + geom_col()
  g <- g + ylim(0, 1)
  g <- g + labs(x = NULL, y = "H0(単位根過程である)が棄却されなかった割合(5%水準)")
  g <- g + theme_bw()
  g <- g + theme(
    axis.title.y = element_text(size = 9), 
    axis.text.x = element_text(size = 8)
  )
  print(g)
  ggsave(paste0(WORKDIR, "/plotDFtest.1.jpg"), width = 12, height = 8, units = "cm")
}
plotEstB2.2 <- function(dfEstB2, WORKDIR){
  # rhoとbetaの散布図
  
  agRho <- sort(unique(dfEstB2$gRho))
  dfPlot <- dfEstB2 %>%
    mutate(
      fRho = factor(gRho, levels = agRho, labels = paste0("rho=", agRho))
    )
  
  g <- ggplot(data = dfPlot, aes(x = gEstBeta, y = gEstRho))
  g <- g + geom_vline(xintercept = 1, color = "red")
  g <- g + geom_hline(
    data = dfPlot %>% distinct(fRho, gRho),
    aes(yintercept = gRho),
    color = "red"
  )
  g <- g + geom_point(alpha = 0.3, size = 1)
  g <- g + facet_wrap(~ fRho, ncol = 6)
  g <- g + labs(x = "hat(beta)", y = "hat(phi)", title = "B2: stationary AR(1) error, MLE")
  g <- g + theme_bw()
  print(g)
  ggsave(paste0(WORKDIR, "/plotB2.2.jpg"), width = 12, height = 8, units = "cm")
}
plotEstStat.1 <- function(dfEstStat, WORKDIR){
  # plot by fApproach

  library(patchwork)
  
  g1 <- ggplot(
    data = dfEstStat, 
    aes(y = gMean, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g1 <- g1 + geom_hline(yintercept = 1)
  g1 <- g1 + geom_text(size=3)
  g1 <- g1 + geom_line()
  g1 <- g1 + labs(x = "rho", y = "mean(hat(beta))")
  g1 <- g1 + scale_color_discrete(guide = FALSE)
  g1 <- g1 + facet_grid(~ fApproach)
  g1 <- g1 + theme_bw()
  g1 <- g1 + theme(
    axis.text.x = element_text(size = 6)
  )
  # print(g1)
  
  g2 <- ggplot(
    data = dfEstStat, 
    aes(y = gRMSE, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g2 <- g2 + geom_text(size=3)
  g2 <- g2 + geom_line()
  g2 <- g2 + labs(x = "rho", y = "RMSE(hat(beta))")
  g2 <- g2 + scale_color_discrete(guide = FALSE)
  g2 <- g2 + facet_grid(~ fApproach)
  g2 <- g2 + theme_bw()
  g2 <- g2 + theme(
    axis.text.x = element_text(size = 6)
  )
  # print(g2)
  
  g <- g1 + g2 + plot_layout(ncol = 1)
  print(g)
  ggsave(paste0(WORKDIR, "/plotEstStat.1.jpg"), width = 12, height = 8, units = "cm")
  
}
plotEstStat.2 <- function(dfEstStat, WORKDIR){
  # plot by fEstimator
  
  library(patchwork)
  
  g1 <- ggplot(
    data = dfEstStat, 
    aes(y = gMean, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g1 <- g1 + geom_hline(yintercept = 1)
  g1 <- g1 + geom_text()
  g1 <- g1 + geom_line()
  g1 <- g1 + labs(x = "rho", y = "mean(hat(beta))")
  g1 <- g1 + scale_color_discrete(guide = FALSE)
  g1 <- g1 + facet_grid(~ fEstimator)
  g1 <- g1 + theme_bw()
  print(g1)
  
  g2 <- ggplot(
    data = dfEstStat, 
    aes(y = gRMSE, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g2 <- g2 + geom_text()
  g2 <- g2 + geom_line()
  g2 <- g2 + labs(x = "rho", y = "RMSE(hat(beta))")
  g2 <- g2 + scale_color_discrete(guide = FALSE)
  g2 <- g2 + facet_grid(~ fEstimator)
  g2 <- g2 + theme_bw()
  # print(g2)
  
  g <- g1 + g2 + plot_layout(ncol = 1)
  print(g)
  
}
plotEstStat.3 <- function(dfEstStat, WORKDIR){
  # approach 2-3
  
  g <- ggplot(
    data = dfEstStat %>% filter(nModel %in% c(2,3,4,6)), 
    aes(y = gRMSE, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g <- g + geom_text()
  g <- g + geom_line()
  g <- g + labs(x = "rho", y = "RMSE(hat(beta))")
  g <- g + scale_color_discrete(guide = FALSE)
  # g <- g + facet_grid(~ fApproach)
  g <- g + theme_bw()
  print(g)
  ggsave(paste0(WORKDIR, "/plotEstStat.3.jpg"), width = 12, height = 8, units = "cm")
  

}
plotEstStat.4 <- function(dfEstStat, WORKDIR){
  # bayesians
  
  g <- ggplot(
    data = dfEstStat %>% filter(nModel %in% c(3,7,9,10)), 
    aes(y = gRMSE, x = gRho, label = as.character(fModel), group = fModel, color = fModel)
  )
  g <- g + geom_text()
  g <- g + geom_line()
  g <- g + labs(x = "rho", y = "RMSE(hat(beta))")
  g <- g + scale_color_discrete(guide = FALSE)
  # g <- g + facet_grid(~ fApproach)
  g <- g + theme_bw()
  print(g)
  ggsave(paste0(WORKDIR, "/plotEstStat.4.jpg"), width = 12, height = 8, units = "cm")
  
  
}
# = = = = = = 

## set directory
## BASEDIR <- "/hoge/hoge"
## WORKDIR <- "/hoge/hoge"

library(tidyverse)

# dfData <- makeData.1 ()
# write_rds(dfData, paste0(BASEDIR, "/dfData.rds"))
# dfData <- read_rds(paste0(BASEDIR, "/dfData.rds"))
# 
## dfDFtest <- makeDFtest.1 (dfData)
# write_rds(dfDFtest, paste0(BASEDIR, "/dfDFtest.rds"))
# dfDFtest <- read_rds(paste0(BASEDIR, "/dfDFtest.rds"))

# dfEstA1 <- makeEstA1.1 (dfData)
# write_rds(dfEstA1, paste0(BASEDIR, "/dfEstA1.rds"))
# dfEstA1 <- read_rds(paste0(BASEDIR, "/dfEstA1.rds"))

# dfEstA3 <- makeEstA3.1 (dfData)
# write_rds(dfEstA3, paste0(BASEDIR, "/dfEstA3.rds"))
# dfEstA3 <- read_rds(paste0(BASEDIR, "/dfEstA3.rds"))

# dfEstB2 <- makeEstB2.1 (dfData)
# write_rds(dfEstB2, paste0(BASEDIR, "/dfEstB2.rds"))
# dfEstB2 <- read_rds(paste0(BASEDIR, "/dfEstB2.rds"))

# dfEstB3 <- makeEstB3.1 (dfData)
# write_rds(dfEstB3, paste0(BASEDIR, "/dfEstB3.rds"))
# dfEstB3 <- read_rds(paste0(BASEDIR, "/dfEstB3.rds"))

# dfEstB4 <- makeEstB4.1 (dfEstB2, dfEstB3, dfDFtest)
# write_rds(dfEstB4, paste0(BASEDIR, "/dfEstB4.rds"))
# dfEstB4 <- read_rds(paste0(BASEDIR, "/dfEstB4.rds"))

# dfEstC2 <- makeEstC2.1 (dfData)
# write_rds(dfEstC2, paste0(BASEDIR, "/dfEstC2.rds"))
# dfEstC2 <- read_rds(paste0(BASEDIR, "/dfEstC2.rds"))

# dfEstD5 <- makeEstD5.1 (dfData)
# write_rds(dfEstD5, paste0(BASEDIR, "/dfEstD5.rds"))
# dfEstD5 <- read_rds(paste0(BASEDIR, "/dfEstD5.rds"))

# dfEstE5 <- makeEstE5.1 (dfData, BASEDIR, WORKDIR)
# write_rds(dfEstE5, paste0(BASEDIR, "/dfEstE5.rds"))
# dfEstE5 <- read_rds(paste0(BASEDIR, "/dfEstE5.rds"))

# library("rstan")
# options(mc.cores = parallel::detectCores())
# rstan_options(auto_write = TRUE)
# oModel_F2 <- stan_model(file = 'EstF2.stan')
# oModel_F5 <- stan_model(file = 'EstF5.stan')
# 
# dfEstF2 <- makeEstF.1 (dfData, oModel_F2)
# write_rds(dfEstF2, paste0(BASEDIR, "/dfEstF2.rds"))
# dfEstF2 <- read_rds(paste0(BASEDIR, "/dfEstF2.rds"))

# dfEstF5 <- makeEstF.1 (dfData, oModel_F5)
# write_rds(dfEstF5, paste0(BASEDIR, "/dfEstF5.rds"))
# dfEstF5 <- read_rds(paste0(BASEDIR, "/dfEstF5.rds"))

# dfEstStat <- makeEstStat.1(
#   dfEstA1, dfEstA3, dfEstB2, dfEstB3, dfEstB4, dfEstC2, dfEstD5,
#   dfEstE5, dfEstF2, dfEstF5
# )
# write_rds(dfEstStat, paste0(BASEDIR, "/dfEstStat.rds"))
# dfEstStat <- read_rds(paste0(BASEDIR, "/dfEstStat.rds"))

# plotData.1 <- plotData.1 (dfData, WORKDIR)
# plotDFtest.1 (dfDFtest, WORKDIR)
# plotEstB2.2 (dfEstB2, WORKDIR)

# plotEstStat.1 (dfEstStat, WORKDIR)
# plotEstStat.2 (dfEstStat, WORKDIR)
# plotEstStat.3 (dfEstStat, WORKDIR)
plotEstStat.4 (dfEstStat, WORKDIR)
